use_frameworks!

platform :ios, '8.0'

target 'MHWebBrowser_Example' do
  pod 'MHWebBrowser', :path => '../'

  target 'MHWebBrowser_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
